# Generated by Django 3.1.2 on 2020-11-21 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pictures',
            old_name='state',
            new_name='culka',
        ),
    ]
